//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeaderProject
    {
        public int HeaderProjectID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ProjectID { get; set; }
    
        public virtual MsProject MsProject { get; set; }
        public virtual MsUser MsUser { get; set; }
    }
}
