//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTask.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TaskProjectEntities : DbContext
    {
        public TaskProjectEntities()
            : base("name=TaskProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HeaderProject> HeaderProjects { get; set; }
        public virtual DbSet<MsProject> MsProjects { get; set; }
        public virtual DbSet<MsUser> MsUsers { get; set; }
    
        public virtual ObjectResult<sp_getOneUserAuth_Result> sp_getOneUserAuth(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getOneUserAuth_Result>("sp_getOneUserAuth", usernameParameter);
        }
    
        public virtual ObjectResult<sp_getUserAuth_Result> sp_getUserAuth(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getUserAuth_Result>("sp_getUserAuth", usernameParameter, passwordParameter);
        }
    }
}
