//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItemTask
    {
        public int ItemTaskID { get; set; }
        public Nullable<int> ItemTaskUserID { get; set; }
        public Nullable<int> ItemWorkID { get; set; }
        public string ItemTaskName { get; set; }
        public string ItemTaskState { get; set; }
    
        public virtual MsUser MsUser { get; set; }
        public virtual WorkItem WorkItem { get; set; }
    }
}
