//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkItem()
        {
            this.WorkItemTasks = new HashSet<WorkItemTask>();
        }
    
        public int WorkItemID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string WorkItemName { get; set; }
        public string WorkItemState { get; set; }
        public Nullable<System.DateTime> WorkItemStartDate { get; set; }
        public Nullable<System.DateTime> WorkItemEndDate { get; set; }
    
        public virtual MsProject MsProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkItemTask> WorkItemTasks { get; set; }
    }
}
